{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-lab-chart.fullname" . }}-db-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "devops-lab-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.user }}
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  {{- end }}
stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_SSL: {{ .Values.database.ssl | quote }}
{{- end }}
